#ifndef FASTCGIPP_CONFIG
#define FASTCGIPP_CONFIG

#define FASTCGIPP_VERSION "@VERSION@"
#define FASTCGIPP_@SYSTEM@
#define FASTCGIPP_BUILD_TIME "@BUILD_TIME@"
#define FASTCGIPP_LOG_LEVEL @LOG_LEVEL@

#endif
